# Generated by Django 3.0 on 2019-12-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='collegeimage',
            field=models.ImageField(upload_to='college/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentimage',
            field=models.ImageField(upload_to='student/'),
        ),
    ]
